spring.application.name=orm-learn-handson2
spring.datasource.url=jdbc:h2:mem:ormlearn;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
logging.level.com.cognizant.ormlearn=DEBUG
logging.level.org.hibernate.SQL=DEBUG

server.port=2030